version: '3'
services:
  db:
    container_name:
      bothub-test-db
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    networks:
      - bothub-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    container_name: bothub-server
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV}
    networks:
      - bothub-network

networks:
  bothub-network:

volumes:
  pgdata:
